# Created with YamlCreate.ps1 v2.4.3 $debug=AUSU.CRLF.7-4-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Oracle.VirtualBox
PackageVersion: 7.1.4
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --msiparams "INSTALLDIR="<INSTALLPATH>""
  Custom: -msiparams REBOOT=ReallySuppress
InstallerSuccessCodes:
- 3010
UpgradeBehavior: uninstallPrevious
FileExtensions:
- ova
- ovf
- vdi
- vhd
- vmdk
AppsAndFeaturesEntries:
- DisplayName: Oracle VirtualBox 7.1.4
Installers:
- Architecture: x86
  InstallerUrl: https://download.virtualbox.org/virtualbox/7.1.4/VirtualBox-7.1.4-165100-Win.exe
  InstallerSha256: F970E275F59EEEB129AAB88A78DAE80784370742B5051650A7926C9EA64AFEAC
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://download.virtualbox.org/virtualbox/7.1.4/VirtualBox-7.1.4-165100-Win.exe
  InstallerSha256: F970E275F59EEEB129AAB88A78DAE80784370742B5051650A7926C9EA64AFEAC
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.9.0

